---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../creds/aws_big_creds.yaml

  vars:
    uri_method: POST
    bigip_addr: "3.10.147.142"

  tasks:
    - name: REST CALL TO BIG-IP
      uri:
        url: "https://{{ bigip_addr }}/mgmt/shared/appsvcs/declare"
        method: "{{ uri_method }}"
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        body: "{{ lookup('file','./as3-dec.json') }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
...